apiVersion: v1
kind: ServiceAccount
metadata:
  name: hango-apiplane
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hango-apiplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hango-apiplane
    namespace: {{ .Values.namespace }}