---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-e2e-app
  namespace: {{ .Values.demo_namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-e2e-app
      name: istio-e2e-app
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: istio-e2e-app
        name: istio-e2e-app
        security.istio.io/tlsMode: istio
        version: v1
    spec:
      containers:
      - args:
        - --port
        - "80"
        - --port
        - "8080"
        - --port
        - "90"
        - --port
        - "9090"
        - --grpc
        - "70"
        - --grpc
        - "7070"
        - --port
        - "3333"
        - --version
        - v1
        image: "{{ .Values.images.e2e_image }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 3333
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: app
        ports:
        - containerPort: 3333
          name: tcp-health-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: tcp-health-port
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30